### ISSUE TITLE
Collaborators

### ISSUE THREAD

**Issue by timjs** [timjs/itasks-ide#1]
@RinusPlasmeijer: krijg je dit?

**Comment by RinusPlasmeijer** [comment]
ja...

From: Tim Steenvoorden 
Sent: Thursday, March 3, 2016 11:29 AM
To: timjs/itasks-ide 
Cc: RinusPlasmeijer 
Subject: [itasks-ide] Collaborators (#1)

@RinusPlasmeijer: krijg je dit?

**Comment by timjs** [comment]
Ah mooi, dan voeg ik je aan deze projecten toe!

Groetjes,
Tim

Op do 3 mrt. 2016 om 12:00 schreef RinusPlasmeijer <notifications@github.com
>:

> ja...
>
> From: Tim Steenvoorden
> Sent: Thursday, March 3, 2016 11:29 AM
> To: timjs/itasks-ide
> Cc: RinusPlasmeijer
> Subject: [itasks-ide] Collaborators (#1)
>
> @RinusPlasmeijer: krijg je dit?
>
> —
> Reply to this email directly or view it on GitHub.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/timjs/itasks-ide/issues/1#issuecomment-191707362>.
>
-- 
Mr. T.J. Steenvoorden, MSc

PhD Student | Radboud University Nijmegen
Faculty of Science | Department of Software Science
Toernooiveld 212 | 6525 EC | Nijmegen
+31 24 365 22 91 | t.steenvoorden@cs.ru.nl
